language: generic

notifications:
  email: false

jobs:
  include:
    - name: Detention Service
      language: node_js
      node_js: 12
      cache: npm
      env: TARGET=service
    - name: Client - Ruby RSpec
      language: ruby
      rvm: 2.6
      cache: bundler
      env: TARGET=clients/ruby/rspec

script: if .travis/build.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "Building '$TARGET' ..." && cd $TARGET && scripts/ci.sh; else echo "No changes detected in '$TARGET'; skipping build."; fi
